server:
  port: 9106
spring:
  application:
    name: hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/
  instance:
    prefer-ip-address: true  #表示将注解的IP注册到Eureka Server
turbine:
  app-config: MICROSERVICE-CONSUMER-MOVIE-1,MICROSERVICE-CONSUMER-MOVIE-2
  cluster-name-expression: "'default'"