server:
  port: 9102
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    username: root
    password: abc@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1014ie345y164lbho.mysql.rds.aliyuncs.com:3306/provideruser?useUnicode=true&characterEncoding=utf8
  application:
    name: microservice-provider-user  #注册到Eureka Server上的应用名称

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/
  instance:
    prefer-ip-address: true  #表示将注解的IP注册到Eureka Server
