server:
  port: 9103

spring:
  application:
    name: microservice-consumer-movie  #注册到Eureka Server上的应用名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/
  instance:
    prefer-ip-address: true  #表示将注解的IP注册到Eureka Server